### ISSUE TITLE
Making Tailwindcss pick the styles in JS components

### ISSUE THREAD

**Issue by germanftorres** [bep/hugo-testing-tailwindcss-v4#2]
Hi, 

I'm trying out the hugo & tailwindcss 4.0 integration (with alpha-26) and cannot make it pickup the styles defined in JS files inside assets directory. I'm using an imported module-based theme, and stock styles used in the theme layout templates are picked up correctly by tailwindcss. In contrast styles used in JS components (inside assets folder) are not being picked up by tailwindcss.

I would assume that in this integration, tailwindcss would be run in the context of hugo and would see the virtual union filesystem and do it's autodetect logic which I think it includes all js files. Any hint on how to make it work?

Thanks!

**Comment by bep** [comment]
TailwindCSS 4 is still in alpha, and I don't have time to answer questions (esp. those I don't have a straight answer for). You can try to come back with an issue after v4 release, and I may have an answer for you.

**Comment by germanftorres** [comment]
For anyone trying out `css.TailwindCSS` during alpha in Hugo:

My issue with Tailwind's new autodetection logic is occuring when the JS files are mounted from a hugo module into the main project and tailwind is invoked from within the new `css.TailwindCSS` Hugo function.

Somehow TailwindCSS v4 is unable to see these files if they come from an external module using the virtual union file system. If I place the files directly in the main project, not imported from a module, `css.TailwindCSS` scans the JS files and extracts the used classes to create the final css.

I was able to work around my issue using the new `@source` directive that is available directly in the css file instead of the traditional tailwind.config.js configuration. 

This works and makes `css.TailwindCSS` find all the source js and html files:
```css
@import "tailwindcss";

@source './public/**/*.{js, html}';  

@theme {
   ...
}
```

Surprisingly, this doesn't work. Using following directive, `css.TailwindCSS` doesn't find the classes present in the javascript source files:
```css
@import "tailwindcss";

@source './layouts/**/*.html'; 
@source './assets/js/**/*.js';

@theme {
   ...
}
```

May be something with the execution context that is created from the hugo side and passed to the tailwindcss cli?

I hope this helps to work around any similar issue till things settle down.
