### ISSUE TITLE
How to install Prose (typography)?

### ISSUE THREAD

**Issue by icedogas** [bep/hugo-testing-tailwindcss-v4#5]
Hello, I used to use this version https://github.com/bep/hugo-starter-tailwind-basic and the typography worked, but it seems not to in this one.

I tried installing it via npm with the following configuration:

```
// tailwind.config.js
const typography = require('@tailwindcss/typography');

module.exports = {
  content: [
    './layouts/**/*.{html,js}',  
  ],
  theme: {
    extend: {},
  },
  plugins: [typography],
};
```
but the prose styles are not appearing. Could you please help me figure out what I'm doing wrong?

**Comment by bep** [comment]
Try add this to your entry stylesheet:

```css
@import "tailwindcss";
@plugin "@tailwindcss/typography";
```

The above works for me with the latest beta.

**Comment by icedogas** [comment]
Thank you very much, it worked perfectly.
